Categories:
    - Money
License: MIT
AuthorName: Ava's DAO
AuthorEmail: support@avasdao.org
WebSite: https://avagogo.io
SourceCode: https://github.com/modenero/avagogo
IssueTracker: https://github.com/modenero/avagogo/issues
Changelog: https://github.com/modenero/avagogo/releases

AutoName: Ava GoGo
Summary: Ava GoGo is awesome...
Description: |-
    Ava GoGo is a ...

    Ava Gogo ! Ad tempor quid culpa consequat si legam fabulas tractavissent e eram ad constias 
    do aliqua, ne aliquip imitarentur. A do illustriora, si sed illustriora qui
    ipsum se si aliqua cernantur hic nisi voluptate se eiusmod iis vidisse
    distinguantur non possumus, senserit aut sint eu singulis iis sint nostrud si ut
    enim consequat probant.

RepoType: git
Repo: https://github.com/modenero/avagogo

AntiFeatures:
    - Tracking

Builds:
  - versionName: 22.6.2
    versionCode: 20220602
    commit: v22.6.2
    subdir: android/app/
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y -t stretch-backports npm
    init: npm install
    gradle:
      - yes
    rm:
      - node_modules/react-native-check-app-install/example/
      - node_modules/react-native-fast-image/ios/
    prebuild:
      - truncate -s 0 ../../node_modules/@react-native-community/cli/build/commands/server/external/xsel
      - "sed -i -e '/import privateKeys/d' -e '/privateKeys: privateKeys/d' ../../app/config/index.js"
    scanignore:
      - android/build.gradle
      - node_modules/react-native-check-app-install/android/build.gradle
      - node_modules/react-native-track-player/android/build.gradle
    scandelete:
      - node_modules/

  - versionName: 1.x.x
    versionCode: 1337
    commit: v1.x.x
    subdir: android/app
    sudo:
      - sysctl fs.inotify.max_user_watches=524288
      - curl -Lo node.tar.xz https://nodejs.org/dist/v10.18.1/node-v10.18.1-linux-x64.tar.xz
      - echo "8cc40f45c2c62529b15e83a6bbe0ac1febf57af3c5720df68067c96c0fddbbdf node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v10.18.1-linux-x64/. /usr/local/
      - npm -g install yarn
    init: yarn install
    gradle:
      - yes
    scanignore:
      - android/build.gradle
      - node_modules/jsc-android
      - node_modules/react-native/android/com/facebook/react/react-native/*/
      - node_modules/react-native-appearance/android/build.gradle
      - node_modules/react-native-reanimated/android/build.gradle
      - node_modules/react-native-safe-area-context/android/build.gradle
      - node_modules/react-native-screens/android/build.gradle
      - node_modules/react-native-sodium/libsodium/*/lib/libsodium.so
      - node_modules/react-native-vector-icons/android/build.gradle
      - node_modules/@react-native-community/async-storage/android/build.gradle
      - node_modules/@react-native-community/masked-view/android/build.gradle
      - node_modules/@react-native-community/netinfo/android/build.gradle
    scandelete:
      - node_modules/
    ndk: r21d

MaintainerNotes: |-
    `scanignore` is used to allow the "node_modules/react-native/android"
    local Maven repository.

    Summary and Description are maintained by upstream using fastlane in
    the source repo:
    https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots

AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
CurrentVersion: 22.6.2
CurrentVersionCode: 20220602
